- name: ensure haproxy is installed
  package:
    name: haproxy
    state: present

- name: set sebooleans
  become: true
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - haproxy_connect_any
    - nis_enabled

- name: template haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  become: true
  register: haproxycfg
  vars:
    query: "[?name == 'esxi_hosts' && type=='metal_device'].instances | [0]"
    esxi_host: "{{ eq_resources | json_query(query) | first }}"

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: true
  become: true
  when:
    - haproxycfg.changed

