- name: template metalvpn nmcli connection
  template:
    src: "metalvpn.connection.j2"
    dest: "/etc/NetworkManager/system-connections/metalvpn.nmconnection"
    mode: 0600
  become: true
  register: nmcli_conn

- name: copy dispatcher script
  copy:
    src: "ppp-route.sh"
    dest: "/etc/NetworkManager/dispatcher.d/99-ppp0-equinix-route.sh"
    mode: 0755
  become: true

- name: restart nmcli
  service:
    name: NetworkManager
    state: restarted
  when: nmcli_conn.changed
  become: true

- name: start metalvpn
  shell: "nmcli con up metalvpn"
  failed_when:
    - out.rc > 0
    - '"already active" not in out.stderr'
  become: true
  register: out
  until:
    - not out.failed
  retries: 5
  delay: 5
